"""Shared POI icon mappings and reference list."""

# Automatisches Mapping: POI-Typ -> Font Awesome Icon-Name (ohne fa- Präfix)
AUTO_MAPPINGS = {
    # UNTERKUNFT & GASTRO
    "lodging": "bed",
    "restaurant": "utensils",
    "cafe": "coffee",
    "bar": "wine-glass",
    "beer": "beer-mug-empty",
    "biergarten": "beer-mug-empty",
    "fast_food": "burger",
    "ice_cream": "ice-cream",
    "pub": "beer-mug-empty",

    # EINZELHANDEL & SERVICES
    "shop": "store",
    "grocery": "basket-shopping",
    "bakery": "bread-slice",
    "butcher": "meat",
    "alcohol_shop": "wine-bottle",
    "clothing_store": "shirt",
    "hairdresser": "scissors",
    "laundry": "soap",

    # GESUNDHEIT
    "hospital": "hospital",
    "doctors": "user-doctor",
    "pharmacy": "prescription-bottle",
    "dentist": "tooth",
    "veterinary": "paw",

    # BILDUNG
    "school": "school",
    "college": "graduation-cap",
    "library": "book",
    "kindergarten": "child",

    # ÖFFENTLICHE EINRICHTUNGEN
    "town_hall": "landmark",
    "post": "envelope",
    "police": "shield",
    "fire_station": "fire-extinguisher",
    "prison": "lock",
    "office": "building",
    "community_centre": "users",
    "public_building": "building-columns",

    # KULTUR & FREIZEIT
    "museum": "building-columns",
    "art_gallery": "palette",
    "theatre": "masks-theater",
    "cinema": "film",
    "castle": "chess-rook",
    "monument": "monument",
    "attraction": "star",
    "theme_park": "ferris-wheel",
    "zoo": "hippo",
    "aquarium": "fish",
    "music": "music",
    "hackerspace": "laptop-code",

    # RELIGIÖS
    "place_of_worship": "place-of-worship",

    # VERKEHR & INFRASTRUKTUR
    "parking": "square-parking",
    "bicycle_parking": "bicycle",
    "motorcycle_parking": "motorcycle",
    "fuel": "gas-pump",
    "bus": "bus",
    "railway": "train",
    "aerialway": "cable-car",
    "ferry_terminal": "ferry",
    "gate": "door-open",
    "lift_gate": "bars",
    "bollard": "road-barrier",
    "cycle_barrier": "bars",
    "stile": "stairs",
    "sally_port": "door-closed",
    "toll_booth": "money-bill",
    "border_control": "passport",
    "entrance": "door-open",
    "harbor": "anchor",

    # SPORT & RECREATION - Ball-Sportarten
    "pitch": "futbol",
    "stadium": "building",
    "sports_centre": "dumbbell",
    "athletics": "person-running",
    "football": "futbol",
    "soccer": "futbol",
    "basketball": "basketball",
    "volleyball": "volleyball",
    "beachvolleyball": "volleyball",
    "tennis": "table-tennis-paddle-ball",
    "table_tennis": "table-tennis-paddle-ball",
    "handball": "hand",
    "team_handball": "hand",
    "baseball": "baseball",
    "field_hockey": "hockey-puck",
    "hockey": "hockey-puck",
    "rugby_union": "football",
    "badminton": "shuttle-space",

    # SPORT - Wasser
    "swimming": "person-swimming",
    "swimming_pool": "person-swimming",
    "water_park": "water",
    "scuba_diving": "water",
    "water_ski": "person-skiing-nordic",
    "sailing": "sailboat",
    "rowing": "water",
    "canoe": "water",
    "surfing": "water",
    "diving": "water",

    # SPORT - Winter
    "winter_sports": "snowflake",
    "ice_hockey": "hockey-puck",
    "ice_rink": "snowflake",
    "ice_stock": "snowflake",
    "curling": "snowflake",
    "skiing": "person-skiing",
    "skating": "snowflake",
    "toboggan": "sleigh",

    # SPORT - Andere
    "golf": "golf-ball-tee",
    "disc_golf": "compact-disc",
    "cycling": "bicycle",
    "bicycle": "bicycle",
    "running": "person-running",
    "climbing": "mountain",
    "climbing_adventure": "mountain",
    "archery": "bullseye",
    "shooting": "bullseye",
    "shooting_range": "bullseye",
    "gymnastics": "person-walking",
    "yoga": "spa",
    "judo": "hand-fist",
    "boxing": "hand-fist",
    "wrestling": "hand-fist",
    "equestrian": "horse",
    "horse_racing": "horse",
    "dog_racing": "dog",
    "motor": "car",
    "motocross": "motorcycle",
    "rc_car": "car",
    "karting": "car",
    "skateboard": "person-skateboarding",
    "bmx": "bicycle",
    "paragliding": "plane",
    "free_flying": "plane",
    "model_aerodrome": "plane",
    "orienteering": "compass",
    "paintball": "bullseye",
    "billiards": "circle",
    "table_soccer": "futbol",
    "chess": "chess",
    "bowls": "bowling-ball",
    "boules": "circle",
    "horseshoes": "horse",
    "racquet": "table-tennis-paddle-ball",
    "paddle_tennis": "table-tennis-paddle-ball",
    "long_jump": "person-running",

    # NATUR & PARKS
    "park": "tree",
    "garden": "leaf",
    "playground": "child",
    "picnic_site": "utensils",
    "dog_park": "dog",
    "campsite": "campground",
    "basin": "water",
    "reservoir": "water",

    # UTILITIES & SERVICES
    "atm": "money-bill",
    "toilets": "restroom",
    "drinking_water": "faucet-drip",
    "fountain": "fountain",
    "waste_basket": "trash-can",
    "recycling": "recycle",
    "information": "circle-info",
    "shelter": "house",
    "bench": "chair",
    "telephone": "phone",
    "car": "car",
    "multi": "circle",
}

# Alle POI-Typen aus der Referenz
ALL_POI_TYPES = [
    "lodging", "restaurant", "cafe", "bar", "beer", "biergarten", "fast_food",
    "ice_cream", "pub", "shop", "grocery", "bakery", "butcher", "alcohol_shop",
    "clothing_store", "hairdresser", "laundry", "hospital", "doctors", "pharmacy",
    "dentist", "veterinary", "school", "college", "library", "kindergarten",
    "town_hall", "post", "police", "fire_station", "prison", "office",
    "community_centre", "public_building", "museum", "art_gallery", "theatre",
    "cinema", "castle", "monument", "attraction", "theme_park", "zoo", "aquarium",
    "music", "hackerspace", "place_of_worship", "parking", "bicycle_parking",
    "motorcycle_parking", "fuel", "bus", "railway", "aerialway", "ferry_terminal",
    "gate", "lift_gate", "bollard", "cycle_barrier", "stile", "sally_port",
    "toll_booth", "border_control", "entrance", "harbor", "pitch", "stadium",
    "sports_centre", "athletics", "football", "soccer", "basketball", "volleyball",
    "beachvolleyball", "tennis", "table_tennis", "handball", "team_handball",
    "baseball", "field_hockey", "hockey", "rugby_union", "badminton", "swimming",
    "swimming_pool", "water_park", "scuba_diving", "water_ski", "sailing", "rowing",
    "canoe", "surfing", "diving", "winter_sports", "ice_hockey", "ice_rink",
    "ice_stock", "curling", "skiing", "skating", "toboggan", "golf", "disc_golf",
    "cycling", "bicycle", "running", "climbing", "climbing_adventure", "archery",
    "shooting", "shooting_range", "gymnastics", "yoga", "judo", "boxing",
    "wrestling", "equestrian", "horse_racing", "dog_racing", "motor", "motocross",
    "rc_car", "karting", "skateboard", "bmx", "paragliding", "free_flying",
    "model_aerodrome", "orienteering", "paintball", "billiards", "table_soccer",
    "chess", "bowls", "boules", "horseshoes", "racquet", "paddle_tennis",
    "long_jump", "park", "garden", "playground", "picnic_site", "dog_park",
    "campsite", "basin", "reservoir", "atm", "toilets", "drinking_water",
    "fountain", "waste_basket", "recycling", "information", "shelter", "bench",
    "telephone", "car", "multi",
]
